pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/prasadrsreddy/my-demo_project.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }
}

