pipeline {
    agent any

    tools {
        maven 'Maven-3.8.5' // Use your configured Maven tool in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/prasadrsreddy/my-demo_project.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // sh './deploy.sh' // Optional deployment script
            }
        }
    }
}

